---
abstract: "Parse the output of the iSDC PABX's 'lex a e' command."
author:
  - 'Ron Savage <ron@savage.net.au>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-PABX-ParseLex
provides:
  Data::PABX::ParseLex:
    file: lib/Data/PABX/ParseLex.pm
    version: 1.04
requires:
  Carp: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.04
